#!/bin/bash

DIR=`dirname $0`

# Process
mv ~/.bashrc ~/.bashrc.bak
cp $DIR/.bash* ~/
cp $DIR/.gitconfig ~/
cat $DIR/.profile >> ~/.profile
cp $DIR/.tmux.conf ~/
cp -r $DIR/.vim ~/

# Setup
~/.vim/setup
