#!/bin/bash
DIR=`dirname $0`

# Backuping
rename 's/$/.bak/' ~/.bash*

# Copying
cp $DIR/.bash* ~/
cat $DIR/.profile >> ~/.profile
cp $DIR/.tmux.conf ~/
cp $DIR/.gitconfig ~/
cp -r $DIR/.vim ~/
cp -r $DIR/.terminfo ~/

# Setuping
~/.vim/setup
