#!/bin/sh

VIM_DIR=`dirname $0`

echo "Setting up VIM: in progress"

mkdir -p $VIM_DIR/autoload
curl -fLo $VIM_DIR/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir -p $VIM_DIR/.undo_history

vim "+PlugInstall" "+qa!"

echo "Setting up VIM: done"
