set nocompatible              " be iMproved, required
filetype off                  " required

" TODO: a strange bahaviour of some vundle's filetype plugins (if place it
" after vundle's defenition)
syntax enable

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Plug in bundled scripts
source ~/.vim/startup/plugins.vim

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Load custom settings
source ~/.vim/startup/color.vim
source ~/.vim/startup/mappings.vim
source ~/.vim/startup/settings.vim
